(() => {
  const $ = (s) => document.querySelector(s);
  const modal = $('#adminModal'), body = $('#adminBody');
  let csrf = '', user = null, panelTab = 'overview', pauseDeadline = 0, pauseInterval = null, logCountdownInterval = null, pauseDismissed = false;
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const roleName = { main:'Main Admin', security:'Sicherheitsadmin', uploader:'Uploader' };
  async function api(url, options={}) {
    const headers = new Headers(options.headers || {});
    if (csrf && options.method && options.method !== 'GET') headers.set('x-csrf-token', csrf);
    if (options.body && !(options.body instanceof FormData)) headers.set('Content-Type','application/json');
    const response = await fetch(url,{...options,headers,credentials:'same-origin'});
    let data={}; try { data=await response.json(); } catch {}
    if (!response.ok) throw new Error(data.error || 'Aktion fehlgeschlagen.');
    return data;
  }
  function toast(text) { const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); }
  function openModal() { modal.classList.remove('hidden'); document.body.style.overflow='hidden'; if(user) renderPanel(); else renderLogin(); }
  function closeModal() { modal.classList.add('hidden'); document.body.style.overflow=''; }
  function applySiteSettings(s) {
    if(!s) return;
    const accent=s.accentColor||'#b071ed';
    document.documentElement.style.setProperty('--purple',accent);
    document.documentElement.style.setProperty('--purple2',`color-mix(in srgb, ${accent} 74%, #171321)`);
    document.documentElement.style.setProperty('--brand-glow',`color-mix(in srgb, ${accent} 22%, transparent)`);
    document.documentElement.style.setProperty('--brand-line',`color-mix(in srgb, ${accent} 35%, #30334a)`);
    document.documentElement.dataset.theme=s.theme==='black'?'black':'violet';
    document.querySelectorAll('[data-site-name]').forEach(el=>el.textContent=s.siteName||'Robo Uncopylocked');
    const logo=s.logoHash?`/api/site-logo?v=${encodeURIComponent(s.logoHash)}`:'robo-logo.png';
    document.querySelectorAll('[data-site-logo]').forEach(el=>{el.src=logo;});
    document.querySelectorAll('[data-hero-image]').forEach(el=>{const slot=el.dataset.heroImage;const hash=slot==='featured'?s.heroFeaturedImageHash:s.heroStudioImageHash;const enabled=Boolean(hash);el.classList.toggle('visible',enabled);el.parentElement.classList.toggle('has-custom',enabled);if(enabled)el.src=`/api/site-image/${slot}?v=${encodeURIComponent(hash)}`;else el.removeAttribute('src');});
    const icon=document.querySelector('link[rel="icon"]');if(icon)icon.href=logo;
    document.title=`${s.siteName||'Robo Uncopylocked'} — Community Library`;
    const meta=$('#themeColorMeta'); if(meta)meta.content=s.theme==='black'?'#070707':'#10111d';
    const screen=$('#pauseScreen');
    if(s.pauseActive&&s.pauseUntil&&!pauseDismissed){
      pauseDeadline=s.pauseUntil;$('#pauseTitle').textContent=s.pauseMessage||'Kurze technische Pause';screen.classList.remove('hidden');
      if(pauseInterval)clearInterval(pauseInterval);
      const tick=()=>{const remaining=Math.max(0,Math.ceil((pauseDeadline-Date.now())/1000));$('#pauseCount').textContent=String(remaining);if(!remaining){screen.classList.add('hidden');clearInterval(pauseInterval);pauseInterval=null;}};
      tick();pauseInterval=setInterval(tick,200);
    } else {screen.classList.add('hidden');if(pauseInterval)clearInterval(pauseInterval);pauseInterval=null;}
  }
  async function loadSiteSettings(){try{applySiteSettings(await api('/api/site-settings'));}catch{}}
  function renderLogin(message='') {
    body.innerHTML=`<form id="loginForm" class="admin-form"><label>Benutzername<input name="username" autocomplete="username" required maxlength="24" placeholder="Admin-Benutzername"></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required placeholder="Dein Passwort"></label><div class="admin-message" id="adminMessage">${esc(message)}</div><button class="button button-primary">Sicher anmelden <span>↗</span></button><p class="form-note">Zugänge werden serverseitig geprüft. Zugangsdaten werden nicht in diesem Browser gespeichert.</p></form>`;
    $('#loginForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{const r=await api('/api/login',{method:'POST',body:JSON.stringify({username:form.get('username'),password:form.get('password')})});user=r.user;csrf=r.csrf;renderPanel();toast('Angemeldet.');}catch(err){renderLogin(err.message);}};
  }
  function formUpload() {
    return `<section class="admin-section"><h3>Neue Ressource hochladen</h3><form id="uploadForm" class="admin-form" enctype="multipart/form-data"><label>Titel<input name="title" required minlength="3" maxlength="100" placeholder="Name des Projekts"></label><label>Beschreibung<textarea name="description" maxlength="2000" placeholder="Was ist enthalten? Credits und Nutzungshinweise nicht vergessen."></textarea></label><label>Kategorie<select name="category"><option>Maps</option><option>Modelle</option><option>UI Kits</option><option>Tools</option></select></label><label>Vorschaubild<input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></label><label>Download-Datei<input name="downloadFile" type="file" accept=".zip,.rbxm,.rbxl,.rbxmx,.rbxlx,.glb,.gltf"></label><small class="form-note">Bilder und Dateien bis 20 MB. Uploader-Einsendungen müssen vor der Veröffentlichung geprüft werden.</small><div class="admin-message" id="uploadMessage"></div><button class="button button-primary">Hochladen</button></form></section>`;
  }
  async function renderPanel() {
    if(logCountdownInterval){clearInterval(logCountdownInterval);logCountdownInterval=null;}
    if(!user) return renderLogin();
    const main=user.role==='main', security=user.role==='security';
    const tabs=[['overview','Übersicht'],['upload','Upload']];
    if(main) tabs.unshift(['jarvis','Jarvis']);
    if(main) tabs.push(['accounts','Konten & Upload-Zugänge'],['settings','Website gestalten']);
    if(main||security) tabs.push(['review','Prüfung'],['logs','Logs']);
    if(!tabs.some(t=>t[0]===panelTab)) panelTab='overview';
    body.innerHTML=`<div class="admin-panel"><div class="admin-welcome"><div><b>${esc(user.username)}</b><small>${esc(roleName[user.role]||user.role)} · sicher angemeldet</small></div><button class="button button-quiet small" id="logoutBtn">Abmelden</button></div><div class="admin-tabs">${tabs.map(([id,label])=>`<button class="admin-tab ${panelTab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</div><div id="panelContent"><span class="form-note">Lade Panel…</span></div></div>`;
    $('#logoutBtn').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'});}catch{}user=null;const auth=await api('/api/auth');csrf=auth.csrf;renderLogin();toast('Abgemeldet.');};
    document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{panelTab=b.dataset.tab;renderPanel();});
    const content=$('#panelContent');
    if(panelTab==='jarvis') {
      content.innerHTML=`<section class="admin-section jarvis-panel"><div class="jarvis-heading"><div class="jarvis-orb" aria-hidden="true">J</div><div><h3>Jarvis</h3><p>Dein Website-Assistent</p></div></div><div class="jarvis-messages" id="jarvisMessages" aria-live="polite"><div class="jarvis-message jarvis-answer"><b>Jarvis</b><p>Hallo Boss! Frag mich nach Besuchern, Ressourcen, Downloads, Konten oder den letzten Aktivitäten.</p></div></div><form class="jarvis-form" id="jarvisAskForm"><label for="jarvisQuestion">Deine Frage</label><div><input id="jarvisQuestion" name="question" maxlength="240" required placeholder="Wie viele Leute waren auf unserer Webseite?"><button class="button button-primary" type="submit">Fragen</button></div></form><p class="settings-note">Besucherzahlen zählen Sitzungen auf der Webseite. Einzelne Klicks auf externe Links werden derzeit nicht separat erfasst.</p></section>`;
      const messages=$('#jarvisMessages'), form=$('#jarvisAskForm'), button=form.querySelector('button');
      const addMessage=(kind,name,text)=>{const item=document.createElement('div');item.className=`jarvis-message ${kind}`;const label=document.createElement('b');label.textContent=name;const reply=document.createElement('p');reply.textContent=text;item.append(label,reply);messages.append(item);messages.scrollTop=messages.scrollHeight;};
      form.onsubmit=async e=>{e.preventDefault();const question=new FormData(form).get('question').trim();if(!question)return;addMessage('jarvis-question','Du',question);form.elements.question.value='';button.disabled=true;button.textContent='…';try{const data=await api('/api/admin/jarvis');addMessage('jarvis-answer','Jarvis',answerJarvis(question,data));}catch(err){addMessage('jarvis-answer','Jarvis',`Ich kann die Website-Daten gerade nicht laden. ${err.message}`);}finally{button.disabled=false;button.textContent='Fragen';form.elements.question.focus();}};
      form.elements.question.focus();return;
    }
    if(panelTab==='upload') {content.innerHTML=formUpload();bindUpload();return;}
    if(panelTab==='overview') {
      if(user.role==='uploader') {content.innerHTML=`<section class="admin-section"><h3>Willkommen</h3><p class="form-note">Dein Konto kann Ressourcen einreichen. Veröffentlichungen werden von einem Admin geprüft.</p><button class="button button-primary" id="goUpload">＋ Ressource einreichen</button></section>`;$('#goUpload').onclick=()=>{panelTab='upload';renderPanel();};return;}
      try { const d=await api('/api/admin/overview'); content.innerHTML=`<div class="admin-layout"><div class="admin-stat"><b>${d.stats.resources}</b><span>Ressourcen</span></div><div class="admin-stat"><b>${d.stats.pending}</b><span>Warten auf Prüfung</span></div><div class="admin-stat"><b>${d.visitors}</b><span>Besucher gesamt</span></div></div>${main?`<form id="visitorForm" class="visitor-control"><div><span class="visitor-control-kicker">BESUCHERANZEIGE</span><b>Besucherzahl einstellen</b><small>Der Wert bleibt für alle Besucher synchron.</small></div><label><span class="sr-only">Besucherzahl</span><input name="value" type="number" min="0" max="2147483647" value="${d.visitors}"></label><button class="button button-primary small">Speichern</button></form>`:''}<section class="admin-section"><h3>Letzte Aktivitäten</h3>${activityRows(d.activity)}</section>`;
        $('#visitorForm')?.addEventListener('submit',async e=>{e.preventDefault();try{const value=new FormData(e.currentTarget).get('value');await api('/api/admin/visitors',{method:'POST',body:JSON.stringify({value:Number(value)})});await refreshCounters();toast('Besucherzahl gespeichert.');renderPanel();}catch(err){toast(err.message);}});
      } catch(err) {content.innerHTML=`<p class="admin-message">${esc(err.message)}</p>`;}
      return;
    }
    if(panelTab==='accounts') {
      try {const accounts=await api('/api/admin/users');content.innerHTML=`<section class="admin-section"><h3>Admin- oder Uploader-Zugang anlegen</h3><p class="admin-role-help">Uploader reichen Bilder und Dateien ein. Sicherheitsadmins sehen Logs und Prüfungen. Main Admins erhalten alle Rechte und können weitere Konten verwalten.</p><form id="accountForm" class="admin-form"><label>Benutzername<input name="username" required minlength="3" maxlength="24" pattern="[A-Za-z0-9_-]+" placeholder="z. B. creator_1"></label><label>Startpasswort<input name="password" type="password" required minlength="12" autocomplete="new-password" placeholder="Mindestens 12 Zeichen"></label><label>Kontotyp<select name="role"><option value="uploader">Uploader – nur Inhalte einreichen</option><option value="security">Sicherheitsadmin – Logs und Prüfung</option><option value="main">Main Admin – alle Rechte</option></select></label><div class="admin-message" id="accountMessage"></div><button class="button button-primary">Zugang erstellen</button></form></section><section class="admin-section"><h3>Bestehende Konten</h3><div class="admin-list">${accounts.map(a=>`<div class="admin-row"><span><b>${esc(a.username)}</b><small>${esc(roleName[a.role]||a.role)}</small></span><span class="role-tag ${esc(a.role)}">${esc(roleName[a.role]||a.role)}</span>${a.username.toLowerCase()===user.username.toLowerCase()?'<span class="tag">dein Konto</span>':`<button class="button danger small" data-delete-user="${esc(a.username)}">Löschen</button>`}</div>`).join('')}</div></section>`;
        $('#accountForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/users',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password'),role:f.get('role')})});toast('Konto angelegt.');renderPanel();}catch(err){$('#accountMessage').textContent=err.message;}};
        document.querySelectorAll('[data-delete-user]').forEach(b=>b.onclick=async()=>{if(!confirm(`Konto ${b.dataset.deleteUser} und alle aktiven Anmeldungen wirklich entfernen?`))return;try{const r=await api(`/api/admin/users/${encodeURIComponent(b.dataset.deleteUser)}`,{method:'DELETE'});toast(r.sessionsEnded?'Konto gelöscht und abgemeldet.':'Konto gelöscht.');renderPanel();}catch(err){toast(err.message);}});
      } catch(err){content.innerHTML=`<p class="admin-message">${esc(err.message)}</p>`;} return;
    }
    if(panelTab==='settings') {
      try {
        const s=await api('/api/admin/settings');
        content.innerHTML=`<section class="admin-section"><h3>Marke und Darstellung</h3><div class="settings-preview"><img id="logoPreview" src="${s.logoData||'robo-logo.png'}" alt="Logo-Vorschau"><span><b id="namePreview">${esc(s.siteName)}</b><small>Vorschau für alle Besucher</small></span></div><form id="siteSettingsForm" class="admin-form"><div class="settings-grid"><label>Webseitenname<input name="siteName" required maxlength="48" value="${esc(s.siteName)}"></label><label>Akzentfarbe<input name="accentColor" type="color" value="${esc(s.accentColor)}"></label><label class="wide">Farbschema<select name="theme"><option value="violet" ${s.theme==='violet'?'selected':''}>Schwarz mit Lila</option><option value="black" ${s.theme==='black'?'selected':''}>Reines Schwarz</option></select></label></div><div class="admin-message" id="settingsMessage"></div><button class="button button-primary">Darstellung speichern</button></form><form id="logoForm" class="admin-form"><label>Neues Logo hochladen<input name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/gif" required></label><small class="form-note">PNG, JPG, WebP oder GIF · maximal 2 MB</small><button class="button button-quiet">Logo aktualisieren</button></form></section><section class="admin-section"><h3>Ein-Minuten-Timer</h3><p class="settings-note">Zeigt allen Besuchern einmal pro Tag für genau eine Minute einen Timer. Danach wird er für heute ausgeblendet.</p><div class="admin-form"><button class="button button-primary" id="dailyTimerBtn" ${s.dailyTimerUsed?'disabled':''}>${s.dailyTimerUsed?'Heute bereits verwendet':'Timer für heute starten'}</button><div class="admin-message" id="dailyTimerMessage"></div></div></section><section class="admin-section"><h3>Kurze Pause für alle Besucher</h3><p class="settings-note">Zeigt allen Besuchern für die gewählte Zeit einen schwarzen Pausenbildschirm. Danach erscheint die Website automatisch wieder. Als Main Admin kannst du den Bildschirm mit Esc nur in deinem Browser schließen.</p><form id="pauseForm" class="admin-form"><label class="check-row"><input name="pauseActive" type="checkbox" ${s.pauseActive?'checked':''}> Kurze Pause jetzt starten</label><label>Anzeigetext<input name="pauseMessage" maxlength="120" value="${esc(s.pauseMessage)}" placeholder="Kurze technische Pause"></label><label>Dauer in Sekunden<input name="pauseSeconds" type="number" min="3" max="300" value="${s.pauseSeconds}"></label><div class="admin-message" id="pauseMessageStatus"></div><button class="button button-primary">Pauseneinstellung speichern</button></form></section>`;
        $('#siteSettingsForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({siteName:f.get('siteName'),accentColor:f.get('accentColor'),theme:f.get('theme'),pauseActive:s.pauseActive,pauseSeconds:s.pauseSeconds,pauseMessage:s.pauseMessage})});await loadSiteSettings();toast('Website-Darstellung gespeichert.');renderPanel();}catch(err){$('#settingsMessage').textContent=err.message;}};
        $('#siteSettingsForm').elements.siteName.oninput=e=>$('#namePreview').textContent=e.target.value||'Robo Uncopylocked';
        $('#logoForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/settings/logo',{method:'POST',body:f});await loadSiteSettings();toast('Logo aktualisiert.');renderPanel();}catch(err){$('#settingsMessage').textContent=err.message;}};
        $('#logoForm').elements.logo.onchange=e=>{const file=e.target.files[0];if(file)$('#logoPreview').src=URL.createObjectURL(file);};
        content.insertAdjacentHTML('beforeend',`<section class="admin-section"><h3>Bilder der Startseite</h3><p class="settings-note">Ändere die beiden großen Motive auf der Startseite. PNG, JPG, WebP oder GIF · maximal 5 MB.</p><div class="hero-image-grid"><form class="admin-form hero-image-setting" data-hero-image-form="featured"><b>Featured-Karte</b><div class="hero-image-preview"><img class="${s.heroFeaturedImageData?'':'hidden'}" data-image-preview src="${s.heroFeaturedImageData||''}" alt="Aktuelles Featured-Bild"><span class="${s.heroFeaturedImageData?'hidden':''}">Das Originalmotiv ist aktiv.</span></div><label>Neues Bild<input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif" required></label><button class="button button-primary">Featured-Bild speichern</button><button class="button button-quiet" type="button" data-reset-hero-image="featured" ${s.heroFeaturedImageData?'':'disabled'}>Originalmotiv wiederherstellen</button></form><form class="admin-form hero-image-setting" data-hero-image-form="studio"><b>Studio-Kit-Karte</b><div class="hero-image-preview"><img class="${s.heroStudioImageData?'':'hidden'}" data-image-preview src="${s.heroStudioImageData||''}" alt="Aktuelles Studio-Kit-Bild"><span class="${s.heroStudioImageData?'hidden':''}">Das Originalmotiv ist aktiv.</span></div><label>Neues Bild<input name="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif" required></label><button class="button button-primary">Studio-Kit-Bild speichern</button><button class="button button-quiet" type="button" data-reset-hero-image="studio" ${s.heroStudioImageData?'':'disabled'}>Originalmotiv wiederherstellen</button></form></div></section>`);
        document.querySelectorAll('[data-hero-image-form]').forEach(form=>{const preview=form.querySelector('[data-image-preview]');form.elements.image.onchange=e=>{const file=e.target.files[0];if(file){preview.src=URL.createObjectURL(file);preview.classList.remove('hidden');form.querySelector('.hero-image-preview span').classList.add('hidden');}};form.onsubmit=async e=>{e.preventDefault();try{await api(`/api/admin/settings/hero-image/${form.dataset.heroImageForm}`,{method:'POST',body:new FormData(form)});await loadSiteSettings();toast('Startseitenbild gespeichert.');renderPanel();}catch(err){$('#settingsMessage').textContent=err.message;}};});
        document.querySelectorAll('[data-reset-hero-image]').forEach(button=>button.onclick=async()=>{const slot=button.dataset.resetHeroImage;if(!confirm('Das eigene Bild entfernen und das Originalmotiv wiederherstellen?'))return;try{await api(`/api/admin/settings/hero-image/${slot}`,{method:'DELETE'});await loadSiteSettings();toast('Originalmotiv wiederhergestellt.');renderPanel();}catch(err){$('#settingsMessage').textContent=err.message;}});
        $('#pauseForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({siteName:s.siteName,accentColor:s.accentColor,theme:s.theme,pauseActive:f.has('pauseActive'),pauseSeconds:Number(f.get('pauseSeconds')),pauseMessage:f.get('pauseMessage')})});pauseDismissed=false;await loadSiteSettings();toast(f.has('pauseActive')?'Pause gestartet.':'Pauseneinstellung gespeichert.');renderPanel();}catch(err){$('#pauseMessageStatus').textContent=err.message;}};
        $('#dailyTimerBtn').onclick=async e=>{e.currentTarget.disabled=true;try{await api('/api/admin/daily-timer',{method:'POST',body:'{}'});pauseDismissed=false;await loadSiteSettings();toast('Ein-Minuten-Timer gestartet.');renderPanel();}catch(err){$('#dailyTimerMessage').textContent=err.message;e.currentTarget.disabled=s.dailyTimerUsed;}};
      } catch(err){content.innerHTML=`<p class="admin-message">${esc(err.message)}</p>`;} return;
    }
    if(panelTab==='review') {
      try {const list=await api('/api/admin/resources');content.innerHTML=`<section class="admin-section"><h3>Ressourcen und Downloadzahlen</h3><p class="settings-note">Die Zahl steigt bei jedem erfolgreichen Download automatisch. Als Main Admin kannst du hier den angezeigten Gesamtwert bearbeiten.</p><div class="admin-list">${list.length?list.map(r=>`<div class="admin-row"><span><b>${esc(r.title)}</b><small>${esc(r.author)} · ${esc(r.category)} · ${esc(r.status)} · ${Number(r.downloads).toLocaleString('de-DE')} tatsächliche Downloads</small></span>${main?`<form class="download-count-form" data-download-form="${esc(r.id)}"><label>Downloadzahl<input name="downloads" type="number" min="0" max="2147483647" value="${Number(r.downloads)}" required></label><button class="button button-quiet small">Speichern</button></form>`:''}${r.status!=='published'?`<button class="button button-primary small" data-publish="${esc(r.id)}">Freigeben</button>`:''}${main?`<button class="button danger small" data-delete-resource="${esc(r.id)}">Löschen</button>`:''}</div>`).join(''):'<p class="form-note">Noch keine Ressourcen.</p>'}</div></section>`;
        document.querySelectorAll('[data-download-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const id=form.dataset.downloadForm;const downloads=Number(new FormData(form).get('downloads'));try{await api(`/api/admin/resources/${encodeURIComponent(id)}/downloads`,{method:'PUT',body:JSON.stringify({downloads})});toast('Downloadzahl gespeichert.');loadResources();renderPanel();}catch(err){toast(err.message);}});
        document.querySelectorAll('[data-publish]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/resources/${b.dataset.publish}`,{method:'PATCH',body:JSON.stringify({status:'published'})});toast('Ressource veröffentlicht.');renderPanel();loadResources();}catch(err){toast(err.message);}});
        document.querySelectorAll('[data-delete-resource]').forEach(b=>b.onclick=async()=>{if(!confirm('Ressource endgültig löschen?'))return;try{await api(`/api/admin/resources/${b.dataset.deleteResource}`,{method:'DELETE'});toast('Ressource gelöscht.');renderPanel();loadResources();}catch(err){toast(err.message);}});
      } catch(err){content.innerHTML=`<p class="admin-message">${esc(err.message)}</p>`;} return;
    }
    if(panelTab==='logs') {try{const rows=await api('/api/admin/logs');content.innerHTML=`<section class="admin-section"><h3>Sicherheits- und Aktivitätslogs</h3><p class="settings-note">Jeder Eintrag zeigt die verbleibende Zeit bis zur automatischen Löschung nach zehn Minuten.${main?' Nur Main Admins können sie zusätzlich manuell löschen.':''}</p>${activityRows(rows,main,true)}</section>`;updateLogCountdowns();logCountdownInterval=setInterval(updateLogCountdowns,1000);document.querySelectorAll('[data-delete-log]').forEach(button=>button.onclick=async()=>{if(!confirm('Diesen Logeintrag wirklich löschen?'))return;try{await api(`/api/admin/logs/${encodeURIComponent(button.dataset.deleteLog)}`,{method:'DELETE'});toast('Logeintrag gelöscht.');renderPanel();}catch(err){toast(err.message);}});}catch(err){content.innerHTML=`<p class="admin-message">${esc(err.message)}</p>`;}}
  }
  function activityRows(rows,deletable=false,showCountdown=false) {return `<div class="admin-list" data-log-list>${rows.length?rows.map(a=>`<div class="admin-row" data-log-row><span><b>${esc(a.action)}</b><small>${esc(a.username)} · ${esc(a.detail||'')} · ${new Date(a.created_at).toLocaleString('de-DE')}${showCountdown?` · <span data-log-countdown data-log-expires="${Date.parse(a.created_at)+600000}"></span>`:''}</small></span><span class="role-tag">${esc(a.level||'info')}</span>${deletable?`<button class="button danger small" data-delete-log="${Number(a.id)}">Löschen</button>`:''}</div>`).join(''):'<p class="form-note">Keine Logs vorhanden. Neue Einträge erscheinen hier, sobald wieder Aktivitäten stattfinden.</p>'}</div>`;}
  function jarvisText(value) {return String(value||'').toLowerCase().replace(/ß/g,'ss').normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
  function answerJarvis(question,data) {
    const q=jarvisText(question),stats=data.stats||{},roles=data.usersByRole||{},resources=data.resources||[];
    if(/besuch|geklick|klick|join|drauf|link|traffic/.test(q)) return `Hallo Boss! Die Besucheranzeige steht bei ${Number(data.visitors||0).toLocaleString('de-DE')}. Sie zählt Besuche pro Sitzung. Einzelne Klicks auf einen bestimmten Link werden nicht separat gezählt.`;
    if(/download/.test(q)) {
      const resource=resources.find(item=>q.includes(jarvisText(item.title)));
      if(resource)return `Hallo Boss! „${resource.title}“ wurde ${Number(resource.downloads).toLocaleString('de-DE')} Mal heruntergeladen.`;
      const top=resources.slice(0,3).map(item=>`${item.title} (${Number(item.downloads).toLocaleString('de-DE')})`).join(', ');
      return `Hallo Boss! Insgesamt wurden Ressourcen ${Number(stats.downloads||0).toLocaleString('de-DE')} Mal heruntergeladen.${top?` Am häufigsten: ${top}.`:''}`;
    }
    if(/konto|konten|nutzer|user|admin|uploader/.test(q))return `Hallo Boss! Es gibt ${Number(stats.users||Object.values(roles).reduce((sum,n)=>sum+Number(n||0),0)).toLocaleString('de-DE')} Konten: ${Number(roles.main||0)} Main Admins, ${Number(roles.security||0)} Sicherheitsadmins und ${Number(roles.uploader||0)} Uploader.`;
    if(/log|aktivitaet|passiert|zuletzt/.test(q)) {
      const recent=data.activity||[];
      if(!recent.length)return 'Hallo Boss! Es gibt gerade keine gespeicherten Aktivitäten. Logs werden nach zehn Minuten automatisch gelöscht.';
      return `Hallo Boss! Die letzten Aktivitäten: ${recent.map(item=>`${item.action}${item.detail?` (${item.detail})`:''}`).join('; ')}. Logs werden nach zehn Minuten automatisch gelöscht.`;
    }
    if(/ressource|modell|upload|projekt|pruef|veroeffentlich/.test(q))return `Hallo Boss! Es gibt ${Number(stats.resources||0)} Ressourcen: ${Number(stats.published||0)} veröffentlicht, ${Number(stats.pending||0)} warten auf Prüfung und ${Number(stats.rejected||0)} wurden abgelehnt.`;
    return `Hallo Boss! Ich kann dir die Besucheranzeige, Downloads, Ressourcen, Konten und letzten Aktivitäten nennen. Frag zum Beispiel: „Wie viele Besucher hatten wir?“ oder „Wie viele Downloads hat ${resources[0]?.title||'ein Modell'}?“`;
  }
  function updateLogCountdowns() {
    const list=$('[data-log-list]');
    if(!list)return;
    list.querySelectorAll('[data-log-countdown]').forEach(clock=>{
      const remaining=Number(clock.dataset.logExpires)-Date.now();
      if(!Number.isFinite(remaining)||remaining<=0){clock.closest('[data-log-row]')?.remove();return;}
      const seconds=Math.ceil(remaining/1000);
      clock.textContent=`wird gelöscht in ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;
    });
    if(!list.querySelector('[data-log-row]')){
      list.innerHTML='<p class="form-note">Keine Logs vorhanden. Neue Einträge erscheinen hier, sobald wieder Aktivitäten stattfinden.</p>';
      if(logCountdownInterval){clearInterval(logCountdownInterval);logCountdownInterval=null;}
    }
  }
  function bindUpload() {
    $('#uploadForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const result=await api('/api/resources',{method:'POST',body:new FormData(e.currentTarget)});toast(result.status==='pending'?'Zur Prüfung eingereicht.':'Ressource veröffentlicht.');e.currentTarget.reset();if(result.status==='published')loadResources();panelTab='overview';renderPanel();}catch(err){$('#uploadMessage').textContent=err.message;}finally{button.disabled=false;}};
  }
  async function loadResources() {
    try {const resources=await api('/api/resources');$('#resourceCount').textContent=String(resources.length).padStart(2,'0');$('#emptyState').classList.toggle('hidden',resources.length>0);$('#resourceGrid').innerHTML=resources.map(r=>`<article class="resource-card"><div class="card-image">${r.hasImage?`<img src="/api/resources/${encodeURIComponent(r.id)}/image" alt="${esc(r.title)}">`:'<div class="image-placeholder theme-violet"><span class="placeholder-icon">✦</span></div>'}<span class="badge category">${esc(r.category)}</span></div><div class="card-body"><div class="card-topline"><h3>${esc(r.title)}</h3></div><p class="card-description">${esc(r.description)}</p><div class="card-foot"><span>von <b class="author">${esc(r.author)}</b></span>${r.hasFile?`<a class="button button-quiet small" href="/api/resources/${encodeURIComponent(r.id)}/download">↓ Download (${Number(r.downloads).toLocaleString('de-DE')})</a>`:`<span class="download-count">Bildvorschau</span>`}</div></div></article>`).join('');} catch {}
  }
  async function refreshCounters() {try{const d=await api('/api/visit',{method:'POST',body:'{}'});$('#visitorCount').textContent=Number(d.visitors).toLocaleString('de-DE');}catch{}}
  $('#adminEntry').addEventListener('click',e=>{e.preventDefault();openModal();});
  $('#closeAdmin').addEventListener('click',closeModal);
  modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&user?.role==='main'&&!$('#pauseScreen').classList.contains('hidden')){pauseDismissed=true;$('#pauseScreen').classList.add('hidden');if(pauseInterval)clearInterval(pauseInterval);pauseInterval=null;return;}if(e.key==='Escape')closeModal();});
  (async()=>{try{const auth=await api('/api/auth');user=auth.user;csrf=auth.csrf;await refreshCounters();}catch{}await loadSiteSettings();await loadResources();setInterval(async()=>{if(document.hidden)return;await loadSiteSettings();try{const auth=await api('/api/auth');if(user&&!auth.user){user=null;csrf=auth.csrf;openModal();renderLogin('Dieses Konto wurde entfernt und abgemeldet.');toast('Konto entfernt · Sitzung beendet.');}}catch{}},1800);})();
})();
